date_time: fix reuse of variable which annoyed mypy.
* date_time: fix reuse of variable which annoyed mypy:
  + mypy.....................................................................Failed

    astrotool/date_time.py:573: error: Incompatible types in assignment (expression has type "ndarray[Any,
    dtype[floating[Any]]]", variable has type "List[float]")

    Apparently, jd_start_gregs was first a list, then recycled as an array, which is naughty in mypy's sight.